---
title: "Machine learning paradigms and workflows -- Part 02"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "Overview of ML paradigms and workflows in R"
date: 2025-11-18
draft: false
---

# Pre-lecture activities

::: {.callout-tip}

We will continue with [`tidymodels`](https://www.tidymodels.org/start/), 
so there is nothing else to install for the lecture. However, if you 
want to see a different linear regression model workflow with the `penguins` 
dataset, checkout this tutorial: 

- [Regression in tidymodels](https://cmu-delphi.github.io/delphi-tooling-book/tidymodels-regression.html)

:::


# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- [An Introduction to Statistical Learning](https://www.statlearning.com)

## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

-  Use `tidymodels` as collection of packages for modeling and machine learning using `tidyverse` principles
-  Be able to fit a linear regression model and a random forest model to be used for prediction in supervised learning 
-  Be able to split data into "train" and "test" to reduce overfitting and improve model performance

:::

## Slides 

- [Lecture 07: Machine learning paradgims -- Part 02](https://docs.google.com/presentation/d/1T9Ezz8iBqzCzkfBHWuSntvyD-KfIqacxaS1glgEBsBE/edit?usp=sharing)

# Class activity 

For the rest of the time in class, we will practice implementing more ML
models with the same `penguins` dataset. 

::: callout-note
### Objectives of the activity

- Extend the linear regression example using additional predictors and compare performance
- Understand how a playing with hyperparameters can change model performance 
- Explore whether adding interaction terms improves predictions

:::

For this in-class activity, you can work alone or find a partner. I encourage you 
to find a partner so you can discuss the questions asked below. 

## Question 1

Using `penguins` dataset discussed in class, we will first extend the linear 
regression example using additional predictors and compare the model
performances. Using this dataset, build two linear regression models predicting
`body_mass_g` using:

- Model A: `bill_length_mm` + `species`
- Model B: `bill_length_mm` + `flipper_length_mm` + `species` + `sex`

Use the same train/test split for both models. Then, compare RMSE and R^2 
between Model A and Model B on:

- the training set
- the test set

Think about and discuss these questions with a partner (or to yourself): 

- Which model performs better?
- Did adding predictors help?
- Is there evidence of overfitting?

## Question 2 

In this question, we will use the training set from above, but now we will 
switch to random forests. There is an argument called `mtry = 3` used to identify 
the number of features sampled for each tree. Let's try changing it and we can 
"tune" the this parameter (also known as a "hyperparameter"). We will ask if this
changes the model's performance. 

Using the training dataset, fit three random forest models with 
different `mtry` values:

- `mtry = 2`
- `mtry = 3` 
- `mtry = 5`

For each model:

- Fit on the training data
- Evaluate on the test data (e.g. rmse and rsq)
- Plot `mtry` vs test rmse.

Think about and discuss these questions with a partner (or to yourself): 

- Which `mtry` yields the lowest test rmse?
- Why might increasing `mtry` help or hurt performance?


## Question 3

In this question, fit two linear regression models to predict `body_mass_g`:

- Model without interaction: `body_mass_g ~ bill_length_mm + flipper_length_mm + species`
- Model with interaction: `body_mass_g ~ bill_length_mm * species + flipper_length_mm`

You want want to compare both models on the train and test rmse. Then, create a visualization of predicted vs actual body mass for the test set for each model.

Think about and discuss these questions with a partner (or to yourself): 

- Did adding interactions help?
- Why might interactions between `bill_length_mm` and `species` matter biologically?